config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'messages/index'
  # root to: "messages#index"
  root to: "rooms#index"
  # ルートパスへのアクセスがあったら、messages_controllerのindexアクションが呼び出される
  resources :users, only: [:edit, :update]
  resources :rooms, only: [:new, :create, :destroy] do
    resources :messages, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, unless: :was_attached?
  # のちのRSpecでテストするvalid?類

  def was_attached?
    self.image.attached?
  end


end

app/models/room.rb
class Room < ApplicationRecord
  
  has_many :room_users, dependent: :destroy# Roomとroom_users のアソシエーション
  has_many :users, through: :room_users
  # RoomとUsers のアソシエーションだがジェイウォークのため中間テーブルの room_users を仲介してアソシエーション

  has_many :messages, dependent: :destroy

  validates :name, presence: true
  # のちのRSpecでテストするvalid?類
end

app/models/room_user.rb
class RoomUser < ApplicationRecord
  belongs_to :room
  belongs_to :user
end
# ”誰がどこに参加しているか”を管理するのが中間テーブルの役目
# belongs_toは相手_idが空ではないか？のバリデーション(validates)がデフォなので
# validates :相手, presence: trueの記述は不要

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  # presence: true を設ける⇨空の場合はDBに保存しない
  # nameだけバリデーションなのは、他カラムはdeviseに標準設定されているから、nameは追加の意

  # のちにRSpecでテストするvalid?類

  has_many :room_users
  has_many :rooms, through: :room_users
  # 上記の２行、上・room_usersとのアソシエーション。下・中間テーブルを介してのRoomとのアソシエーション
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller? # 1

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name]) # 1
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @message = Message.new
    @room = Room.find(params[:room_id])
    @messages = @room.messages.includes(:user)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params) # チャットルームに紐づいたメッセージのインスタンス(privateへの引数)
    if @message.save
      redirect_to room_messages_path(@room)
    else
      @messages = @room.messages.includes(:user)
      render :index
    end
    
  end

  private
  def message_params
    # params.require(:message).permit(:content,ここに:image).merge(user_id: current_user.id)
    #                                           imageという名の画像ファイルの保存を許可
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)

  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def new
    @room = Room.new
  end

  def create
    # binding.pry
    @room = Room.new(room_params)
      if @room.save
        redirect_to root_path
      else
        render :new
      end
  end

  def index
    
  end

  def destroy
    room = Room.find(params[:id])
    room.destroy
    redirect_to root_path
  end

  private

  def room_params
    params.require(:room).permit(:name, user_ids: [])
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end


  def update
    if current_user.update(user_params) # 1
      redirect_to root_path
    else
      render :edit
    end 
  end

  private

  def user_params
    params.require(:user).permit(:name, :email) # 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_main_chat.html.erb
<%# 上 %>

<div class="main-top">
  <div class="chat-content">
    <%# <a href="#">Chatタイトル</a> %>
    <div class="content-name">
      <%# Chatタイトル %>
      <%= @room.name %>
    </div>
  </div>
  <div class="chat-end">
    <div class="end-btn">
      <%# <a href="#">チャットを終了する</a> %>
      <%= link_to "チャットを終了する", room_path(@room), method: :delete %>
            
    </div>
  </div>
</div>

<%# 中 %>
<div class="main-center">
  <%= render partial: 'message', collection: @messages %>
</div>


<%# ここから 
<div class="main-center">
  <div class="chat-text">
    <div class="text-users">
      <div class="user-name">
        トム
      </div>
      <div class="text-date">
        2021/10/10(sun) 12:34:56
      </div>
    </div>
    <div class="text-post">
      <div class="post-message">
        こんにちは！
      </div>
    </div>
  </div>

  <div class="chat-text">
    <div class="text-users">
      <div class="user-name">
        サム
      </div>
      <div class="text-date">
        2021/10/10(sun) 22:34:56
      </div>
    </div>
    <div class="text-post">
      <div class="post-message">
        こんばんは！！
      </div>
    </div>
  </div>
</div>
    ここまで、仮記述 %>

<%# 下 %>

<%= form_with model: [@room, @message], class: 'form', local: true do |f| %>
  <div class="main-under">
    <%= f.text_field :content, class: 'input-form', placeholder: "type a message" %>
      <label class="form-image">
        <span class="image-file">画像</span>
        <%= f.file_field :image, class: 'hidden' %> 
      </label>
      <%= f.submit "送信", class: "submit-form" %> 
  </div>
<% end %> %>



<%# 以下見た目のみの記述
<div class="main-under">
  <div class="under-input">
    <input class="input-form" placeholder= "type a message">
    <label class="form-image">
      <span class="image-file">画像</span>
      <input type="file" class="hidden">
    </label>
  </div>
  <input class="submit-form" type="submit" value="送信">
</div>
%>

app/views/messages/_message.html.erb
<div class="main-center">
  <div class="chat-text">
    <div class="text-user">
      <!-- 投稿したユーザー名情報を出力する -->
      <%= message.user.name %>
    </div>
    <div class="text-date">
      <!-- 投稿した時刻を出力する -->
      <%=  l message.created_at %>
    </div>
  </div>
  <div class="text-post">
    <div class="post-message">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= message.content %>
    </div>
      <%# 
       image_tag message.image, class: 'message-image' ←だけだと画像無でも読み込みエラー
                                                           画像有のみimage_tag読み込み
      <%= image_tag message.image, class: 'message-image' if message.image.attached?  ↓イメージのサイズ指定有%>
      <%= image_tag message.image.variant(resize: '500x500'), class: 'message-image' if message.image.attached? %>

  </div>
</div>

app/views/messages/_side_bar.html.erb
<%# 上 %>
<div class="side-top">
  <div class="user-name">
    <%= link_to current_user.name, edit_user_path(current_user) %> 
    <%# <a href="#">トム</a> %>
  </div>
  <div class="create-chat">
    <%# <a href="#">チャットを作成する</a> %>
    <%= link_to "チャットを作成する", new_room_path %>
  </div>
</div>

<%# 下 %>

 <%# 
 <div class="side-main">
  <div class="chat-room-name">
    <a href="#">textroom1</a>
    <a href="#">textroom2</a>
  </div>
 </div> 
 %>


<div class="side-main">
  <% current_user.rooms.each do |room| %>
    <div class="chat-room">
      <div class="room-name">
        <%= link_to room.name, room_messages_path(room) %>
      </div>
    </div>
  <% end %>
  


 <%# 
 <div class="chat-room">
  <div class="room-name">
    <a href="#">textroom2</a>
  </div>
 </div> 
 %>



</div>

app/views/messages/index.html.erb
<%# <h1>Messages#index</h1>
<p>Find me in app/views/messages/index.html.erb</p> %>
<div class="wrapper">
  <div class="l-side">
    <%# 左側 %>
    <%= render "side_bar" %>
  </div>
  <div class="r-main">
    <%# 右側 %>
    <%= render "main_chat" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="wrapper">
  <div class="l-side">
    <%= render "messages/side_bar" %>
    <%# 同ディレクトリ内ならside_barのみでOKだが他ディレクトリのため
        render "指定ファイルのあるディレクトリ/ファイル名"となる 
    %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class='chat-room-form'>
  <h1>新規チャットルーム</h1>
  <%= form_with model: @room, local: true do |f|%>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <%= f.label :チャットルーム名, class: 'chat-room-form__label'%>
      </div>
      <div class='chat-room-form__field--right'>
        <%= f.text_field :name, class: 'chat__room_name chat-room-form__input', placeholder: 'チャットルーム名を入力してください'%>
      </div>
    </div>
    <div class='chat-room-form__field'>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'>
        <label class='chat-room-form__label' for='chat_room_チャットメンバー'>チャットメンバー</label>
      </div>
      <div class='chat-room-form__field--right'>
        <select name="room[user_ids][]">
          <%# <option>チャットするユーザーを選択してください</option>
          <option>ユーザー１</option>
          <option>ユーザー２</option> 仮実装記述%>
          <option value="">チャットするユーザーを選択してください</option>
          <%# <% User.all.each do |user| ←チャット作成主含め全員 ↓主は当然とし、他ユーザーの選択%> 
          <% User.where.not(id: current_user.id).each do |user| %> 
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="room[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='chat-room-form__field'>
      <div class='chat-room-form__field--left'></div>
      <div class='chat-room-form__field--right'>
        <%= f.submit class: 'chat-room-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%# link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>